import '../imports/startup/accounts-config.js';
import '../imports/api/home-net.js';
import '../imports/ui/home.js';
import '../imports/ui/modify.js'
import '../imports/ui/mobile.js'
import '../imports/ui/configure.js'
import '../imports/ui/mainfloor.js'
import '../imports/ui/topfloor.js'
import '../imports/ui/alertmail.js'
